# Generated by Django 4.1.4 on 2022-12-12 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(default='', max_length=100)),
                ('uuid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=1000)),
                ('genres', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('title', models.CharField(default='', max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=1000)),
                ('movies', models.ManyToManyField(related_name='collections', to='collection.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
