# Generated by Django 4.1.4 on 2022-12-11 16:00

from django.db import migrations


def initialize_request_count(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    KeyValueStore = apps.get_model('miscellaneous', 'KeyValueStore')
    KeyValueStore.objects.create(key="request_count", value="0")


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initialize_request_count),
    ]
